
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mll?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8004

mybatis:
#  type-aliases-package: tmy.demo.use.model
  mapper-locations: classpath:mapper/*.xml

mapper:
 # mappers: tmy.demo.*.mapper
  not-empty: false
  identity: MYSQL
  ORDER: BEFORE

spring.thymeleaf.content-type: text/html
spring.thymeleaf.cache: false
spring.thymeleaf.mode: LEGACYHTML5

#控制是否热部署
spring.devtools.restart.enabled: true


